/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TableHockeyClient;

import TableHockey.BallModel;
import java.net.Socket;

/**
 *
 * @author adnanfahed
 */
public class GameScreen extends javax.swing.JFrame {

    GameClient client;

    BallModel ball;

    GamePanel gamePanel;

    /**
     * Creates new form GameScreen
     *
     * @param gameSocket
     */
    public GameScreen(Socket gameSocket) {
        setup(gameSocket);

        gamePanel = new GamePanel();

        getContentPane().add(gamePanel);

        initComponents();
    }

    void setup(Socket gameSocket) {

        var callbacks = new GameClientCallbacks() {
            @Override
            public void setBall(BallModel b) {
                ball = b;
                gamePanel.setBall(b);

            }
        };

        this.client = new GameClient(gameSocket, callbacks);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
